Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true

  ### Database VM ###
  config.vm.define "db01" do |db01|
    db01.vm.box = "eurolinux-vagrant/centos-stream-9"
    db01.vm.box_version = "9.0.48"
    db01.vm.hostname = "db01"
    db01.vm.network "private_network", type: "static", ip: "192.168.56.50"
    db01.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
    db01.vm.provision "shell", inline: <<-SHELL
      #sudo dnf update -y
    SHELL
  end

  ### Memcache VM ###
  config.vm.define "mc01" do |mc01|
    mc01.vm.box = "eurolinux-vagrant/centos-stream-9"
    mc01.vm.box_version = "9.0.48"
    mc01.vm.hostname = "mc01"
    mc01.vm.network "private_network", type: "static", ip: "192.168.56.51"
    mc01.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
    mc01.vm.provision "shell", inline: <<-SHELL
     # sudo dnf update -y
    SHELL
  end

  ### RabbitMQ VM ###
  config.vm.define "rmq01" do |rmq01|
    rmq01.vm.box = "eurolinux-vagrant/centos-stream-9"
    rmq01.vm.box_version = "9.0.48"
    rmq01.vm.hostname = "rmq01"
    rmq01.vm.network "private_network", type: "static", ip: "192.168.56.52"
    rmq01.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
    rmq01.vm.provision "shell", inline: <<-SHELL
     # sudo dnf update -y
    SHELL
  end

  ### Tomcat VM ###
  config.vm.define "app01" do |app01|
    app01.vm.box = "eurolinux-vagrant/centos-stream-9"
    app01.vm.box_version = "9.0.48"
    app01.vm.hostname = "app01"
    app01.vm.network "private_network", type: "static", ip: "192.168.56.53"
    app01.vm.provider "virtualbox" do |vb|
      vb.memory = "3024"
    end
     app01.vm.provision "shell", inline: <<-SHELL
      #sudo dnf update -y
    SHELL
  end

  ### Nginx VM ###
  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/jammy64"
    web01.vm.hostname = "web01"
    web01.vm.network "private_network", type: "static", ip: "192.168.56.54"
    web01.vm.provider "virtualbox" do |vb|
      # vb.gui = true
      vb.memory = "2048"
    end
    web01.vm.provision "shell", inline: <<-SHELL
     # sudo apt-get update -y
     # sudo apt-get upgrade -y
    SHELL
  end

  # ### Grafana VM ###
  # config.vm.define "grafana" do |grafana|
  #   grafana.vm.box = "ubuntu/jammy64"
  #   grafana.vm.hostname = "grafana"
  #   grafana.vm.network "private_network", type: "static", ip: "192.168.56.55"
  #   grafana.vm.provider "virtualbox" do |vb|
  #     vb.memory = "1024"
  #   end
  #   grafana.vm.provision "shell", inline: <<-SHELL
  #     sudo apt-get update
  #     sudo apt-get install -y apt-transport-https software-properties-common wget
  #     sudo mkdir -p /etc/apt/keyrings/
  #     wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor | sudo tee /etc/apt/keyrings/grafana.gpg > /dev/null
  #     echo "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main" | sudo tee -a /etc/apt/sources.list.d/grafana.list
  #     sudo apt-get install grafana -y
  #     sudo apt-get install grafana-enterprise -y
  #     sudo systemctl daemon-reload
  #     sudo systemctl start grafana-server
  #     sudo systemctl enable grafana-server.service
  #     sudo systemctl restart grafana-server
  #   SHELL
  # end
end
